export type Movie = {
  amgArtistId?: string;
  artistId?: number;
  artistName: string;
  artistViewUrl?: string;
  artworkUrl100: string;
  artworkUrl30?: string;
  artworkUrl60: string;
  collectionArtistId?: number;
  collectionArtistName?: string;
  collectionArtistViewUrl?: string;
  collectionCensoredName?: string;
  collectionExplicitness: string;
  collectionHdPrice?: number;
  collectionId?: number;
  collectionName?: string;
  collectionPrice: number;
  collectionViewUrl?: string;
  contentAdvisoryRating?: string;
  country: string;
  currency: string;
  description?: string;
  discCount?: number;
  discNumber?: number;
  hasITunesExtras?: boolean;
  isStreamable?: boolean;
  kind?: string;
  longDescription?: string;
  previewUrl: string;
  primaryGenreName: string;
  releaseDate: string;
  shortDescription?: string;
  trackCensoredName?: string;
  trackCount?: number;
  trackExplicitness?: string;
  trackHdPrice?: number;
  trackHdRentalPrice?: number;
  trackId?: number;
  trackName?: string;
  trackNumber?: number;
  trackPrice?: number;
  trackRentalPrice?: number;
  trackTimeMillis?: number;
  trackViewUrl?: string;
  wrapperType: string;
};

export type QueryResult = {
  resultCount: number;
  results: Movie[];
};
